#!/usr/bin/env bash
# One-shot machine setup for Recon Studio — run this first on a new box.
#
#   ./setup.sh                 create the conda env, install deps, write local.env, run doctor
#   ./setup.sh --env myenv     use a different conda env name (default: rec)
#   ./setup.sh --skip-env      only (re)write local.env + run doctor, don't touch conda
#
# Idempotent and non-destructive: an existing conda env is reused, and an existing
# local.env is NEVER overwritten (the detected values are printed as a diff-style
# suggestion instead, so a machine that's already tuned keeps its settings).
#
# What it does NOT do — these need a GPU and per-machine compilation, so they stay
# manual (see README「一、安裝」):
#   * colmap / ffmpeg (system packages or source builds)
#   * the trainer envs: GS-2M's CUDA submodules, LichtFeld-Studio's cmake build
# `./run.sh --doctor` at the end tells you exactly which of those are still missing.
set -euo pipefail
cd "$(dirname "$0")"

CONDA_ENV=rec
SKIP_ENV=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)      CONDA_ENV="$2"; shift 2 ;;
    --skip-env) SKIP_ENV=1; shift ;;
    # Print the whole header block, however long it grows — a hardcoded line
    # range silently truncates the help text the moment the comment is edited.
    -h|--help)  sed -n '/^set -/q;2,$p' "$0"; exit 0 ;;
    *)          echo "unknown option: $1 (see --help)" >&2; exit 2 ;;
  esac
done

. ./tools/detect.sh          # same detection run.sh uses at every startup

say()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
note() { printf '    %s\n' "$*"; }

# --------------------------------------------------------------------------- #
say "偵測這台機器"
CONDA_ROOT="$(detect_conda_root)"
DATA_DISK="$(detect_data_disk)"
FFMPEG="$(detect_ffmpeg "$DATA_DISK")"
DATA_DIR="$(default_data_dir "$DATA_DISK")"

note "conda root : ${CONDA_ROOT:-（找不到！）}"
note "資料磁碟   : ${DATA_DISK:-（找不到夠大的非 root 掛載點,退回 \$HOME）}"
note "ffmpeg     : $FFMPEG"
note "job 資料夾 : $DATA_DIR"

[[ -n "$CONDA_ROOT" ]] || {
  echo "找不到 conda。先裝 miniconda,或設 CONDA_ROOT=/path/to/conda 再跑一次。" >&2
  exit 1
}

# --------------------------------------------------------------------------- #
CONDA="$CONDA_ROOT/bin/conda"
ENVPY="$CONDA_ROOT/envs/$CONDA_ENV/bin/python"
if [[ "$SKIP_ENV" == 1 ]]; then
  say "跳過 conda env（--skip-env）"
else
  if [[ -x "$ENVPY" ]]; then
    say "conda env '$CONDA_ENV' 已存在 — 只更新套件"
  else
    say "建立 conda env '$CONDA_ENV'（python 3.10）"
    "$CONDA" create -n "$CONDA_ENV" python=3.10 -y
  fi
  "$CONDA" run -n "$CONDA_ENV" python -m pip install -q -r requirements.txt
  note "面板依賴已安裝/更新（純 Python,不含 torch）"
fi

# --------------------------------------------------------------------------- #
# local.env: write only what auto-detection CAN'T work out, and record everything
# it can as comments.
#
# The distinction matters. run.sh re-runs the same tools/detect.sh functions on
# every startup, so pinning a detected value here doesn't help — it PERMANENTLY
# MASKS the detection. Install an NVDEC ffmpeg next month, or move to a bigger
# disk, and a pinned FFMPEG_BIN / RECON_STUDIO_DATA means run.sh never notices.
# Worse, when detection fails, detect_ffmpeg falls back to the literal `ffmpeg` —
# freezing that would turn "not found yet" into a permanent setting.
#
# CONDA_ROOT is the exception worth pinning: it's stable, and having it set skips
# a `conda info --base` (~0.5s, measured) on every single startup.
write_local_env() {
  cat > "$1" <<EOF
# Recon Studio — this machine's config, generated by ./setup.sh
# 完整可用選項與說明見 local.env.example。
#
# 只寫「偵測不出來 / 要人決定」的項目。註解掉的那些是 run.sh 每次啟動自己會偵測的,
# 寫死反而會遮蔽偵測（之後裝了 NVDEC ffmpeg、換了資料磁碟都不會被發現）。
# 真的要固定某一項,把該行的 # 拿掉即可。

# --- conda（CONDA_ROOT 值得寫死:省下每次啟動一次 conda info --base）---
CONDA_ROOT=$CONDA_ROOT
CONDA_ENV=$CONDA_ENV

# --- server ---
HOST=127.0.0.1
PORT=8077

# --- 本機偵測結果（僅供參考,run.sh 每次啟動都會重新偵測）---
# COLMAP_BIN=colmap                          # 目前解析到: ${DETECTED_COLMAP:-（PATH 上找不到）}
# FFMPEG_BIN=$FFMPEG
# RECON_STUDIO_DATA=$DATA_DIR
# TMPDIR=$(default_tmp_dir "$DATA_DISK")
# RECON_STUDIO_BROWSE_ROOT=$(default_browse_root "$DATA_DISK")

# --- 選用：GCS 雲端搬檔（☁️ 資料 分頁需要,見 local.env.example）---
# CLOUDSDK_CORE_PROJECT=my-gcp-project

# --- 選用：COLMAP 縮圖的平行度。取決於來源檔在哪種磁碟,偵測不出來 ---
# 單顆 HDD 上開太多 worker 會因隨機尋軌而變慢（大檔甜蜜點約 4~6）;SSD/NVMe 可往上加。
# COLMAP_PANEL_RESIZE_WORKERS=6
EOF
}

DETECTED_COLMAP="$(command -v colmap || true)"
if [[ -f local.env ]]; then
  say "local.env 已存在 — 不覆蓋"
  write_local_env local.env.detected
  if cmp -s local.env local.env.detected; then
    note "內容與偵測結果一致"
    rm -f local.env.detected
  else
    note "偵測結果寫到 local.env.detected,要換再自己比對/搬過去："
    note "  diff -u local.env local.env.detected"
  fi
else
  say "產生 local.env"
  write_local_env local.env
  note "如需調整,每個選項的說明在 local.env.example"
fi

# backends.json is intentionally NOT generated: the built-in defaults in
# pipeline/backends.py already cover sibling repos/envs, and an unnecessary local
# override would freeze out params added upstream later (see backends.example.json).
[[ -f backends.json ]] && note "backends.json 存在（本機後端覆蓋設定）" \
                       || note "沒有 backends.json — 內建預設通常就夠（見 backends.example.json）"

# --------------------------------------------------------------------------- #
say "環境檢查"
# Don't let a red light abort the script: the report IS the deliverable here, and
# the remaining work (colmap / trainer builds) is exactly what it's listing.
if ./run.sh --doctor; then
  printf '\n\033[1;32m設定完成 — ./run.sh 就可以啟動了。\033[0m\n'
else
  printf '\n\033[1;33m面板本身裝好了,但上面 FAIL 的項目要先補齊。\033[0m\n'
  printf '安裝步驟見 README「一、安裝」;補好後用 ./run.sh --doctor 再確認。\n'
fi
